# Generated by Django 3.0 on 2020-10-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0002_facilitator_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('interest', models.CharField(choices=[('Team Building', 'Team Building'), ('Digital Marketing', 'Digital Marketing'), ('Talent Empowerment', 'Talent Empowerment'), ('Leadership', 'Leadership'), ('Change Management', 'Change Management'), ('Conflict Resolution', 'Conflict Resolution')], max_length=250)),
                ('abouts', models.CharField(choices=[('None', 'None'), ('Referral', 'Referral'), ('Conference', 'Conference'), ('Networking event', 'Networking event'), ('Search Engine(Yahoo/Google/Bing,etc)', 'Search Engine(Yahoo/Google/Bing,etc)'), ('Email Marketing', 'Email Marketing'), ('Others(please specify below)', 'Others(please specify below')], max_length=250)),
                ('questions_comments', models.TextField()),
            ],
        ),
    ]
